services:
  redis:
    image: redis:7-alpine
    container_name: calculate_pi_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - pi_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calculate_pi_api
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_DB=${REDIS_DB:-0}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - pi_network

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: calculate_pi_worker
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_DB=${REDIS_DB:-0}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - pi_network

networks:
  pi_network:
    driver: bridge
