FROM python:3.13-slim

RUN useradd --create-home --shell /bin/bash app

WORKDIR /home/app

COPY pyproject.toml uv.lock ./

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

COPY . .

RUN uv sync --frozen --no-install-project

RUN chown -R app:app /home/app

USER app

CMD ["uv", "run", "celery", "-A", "app.celery_app", "worker", "--loglevel=info"]

